/** Declaration file generated by dts-gen */
export default function inject (source?: string, attributes?: object): USERDIVETracker.USERDIVE.USERDIVEObject.USERDIVEAgent;

declare namespace USERDIVETracker.USERDIVE {

  type commandCreate = 'create'
  type commandSend = 'send'
  type sendType = 'pageview'

  namespace USERDIVEObject {
    interface USERDIVEAgent {
      (
        command: commandCreate,
        projectId: string,
        settings?: any | 'auto'
      )
      (
        command: commandSend,
        type: sendType,
        page?: string
      )
    }
  }
}
